### ISSUE TITLE
Keycode Error fix?

### ISSUE THREAD

**Issue by l3pt1c** [TobiasPankner/PSN-Unfriender#3]
![Screenshot_2024-12-08-13-25-59-305-edit_com miui gallery](https://github.com/user-attachments/assets/15f302fa-ee0e-4803-9c9a-ccdd971c77f6)

**Comment by TobiasPankner** [comment]
Hi!
Did you enter the npsso token correctly?

**Comment by l3pt1c** [comment]
> Hi! Did you enter the npsso token correctly?

I think I did I went to the psn website got my token and copied and pasted it into the quotations.

**Comment by TobiasPankner** [comment]
You can try to obtain a new token and check again.
By the error, something seems wrong with the current token

**Comment by l3pt1c** [comment]
> You can try to obtain a new token and check again. By the error, something seems wrong with the current token

Alright, I'll try that.
